# @Auth.Api_HostAddress = https://localhost:7153
@Auth.Api_HostAddress = https://schoderauth.azurewebsites.net

### Alive

GET {{Auth.Api_HostAddress}}/
Accept: application/json

### Error

POST {{Auth.Api_HostAddress}}/errors
Accept: application/json
