# @Auth.Api_HostAddress = https://localhost:7153
@Auth.Api_HostAddress = https://schoderauth.azurewebsites.net

### Alive

GET {{Auth.Api_HostAddress}}/api
Accept: application/json

### Error

GET {{Auth.Api_HostAddress}}/error
Accept: application/json
