@Auth.Api_HostAddress = https://localhost:7153
#@Auth.Api_HostAddress = https://schoderauth.azurewebsites.net

### 

POST {{Auth.Api_HostAddress}}/api/login
Content-Type: application/json
{
  "email": "admin",
  "password": "admin"
}

###

POST {{Auth.Api_HostAddress}}/api/register
Content-Type: application/json
{
  "email": "",
  "password": ""
}

###

POST {{Auth.Api_HostAddress}}/api/visitors
Content-Type: application/json

###
