@Auth.Api_HostAddress = https://localhost:7153

### 

POST {{Auth.Api_HostAddress}}/api/login
Content-Type: application/json
{
  "email": "admin",
  "password": "admin"
}

###

POST {{Auth.Api_HostAddress}}/api/logout
Content-Type: application/json

###

POST {{Auth.Api_HostAddress}}/api/register
Content-Type: application/json
{
  "email": "admin",
  "password": "admin"
}

###
