@Formula1.Api_HostAddress = https://localhost:7153

### 

POST {{Formula1.Api_HostAddress}}/api/login
Content-Type: application/json
{
  "email": "admin"
  "password": "admin"
}

###

POST {{Formula1.Api_HostAddress}}/api/logout
Content-Type: application/json

###

POST {{Formula1.Api_HostAddress}}/api/register
Content-Type: application/json
{
  "year": {{year}},
  "round": 1
}

###
