@Auth.Api_HostAddress = https://localhost:7153
# @Auth.Api_HostAddress = https://schoderauth.azurewebsites.net

### Login

POST {{Auth.Api_HostAddress}}/persons/login
Content-Type: application/json
{
  "email": "dietmar@schoder.uk",
  "password": "TESTTEST"
}

### Register

POST {{Auth.Api_HostAddress}}/persons
Content-Type: application/json
{
  "email": "admin4",
  "password": "admin4"
}
